service: track-performance

plugins:
  - serverless-webpack

custom:
  regionAndAccount: us-east-1:251013100663
  secretsArnPrefix: arn:aws:secretsmanager:${self:custom.regionAndAccount}:secret:${self:provider.stage}
  webpack:
    webpackConfig: webpack.config.ts
    packager: yarn
    includeModules: true # Enable auto-packing of external modules

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  memorySize: 128
  timeout: 300
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'}
    STAGE: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "${self:custom.secretsArnPrefix}/wpt/apiKey-*"
        - "${self:custom.secretsArnPrefix}/google/searchConsoleApis/apiKey-*"
    - Effect: Allow
      Action:
        - elasticbeanstalk:DescribeEnvironments
        - elasticbeanstalk:DescribeEvents
        - elasticbeanstalk:DescribeApplicationVersions
        - elasticbeanstalk:DescribeInstancesHealth
        - elasticbeanstalk:DescribeEnvironmentHealth
        - elasticbeanstalk:DescribeApplications
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:ListFunctions
        - lambda:ListVersionsByFunction
        - lambda:ListAliases
        - cloudwatch:GetMetricStatistics
        - cloudwatch:GetMetricData
      Resource: "*"

functions:
  reportPerformance:
    handler: src/reportPerformance.reportPerformance
    events:
      - schedule:
          rate: rate(24 hours)
          enabled: true

package:
  include:
    - src/**
    - secrets/**
  exclude:
    - .webpack

