service: track-performance

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.ts
    packager: yarn
    includeModules: true # Enable auto-packing of external modules

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'development'}
  memorySize: 128
  timeout: 300
  environment:
    NODE_ENV: ${opt:stage, self:provider.stage, 'local'}
    GITHUB_TOKEN: ${file(./secrets/github.json):token}
    WPT_API_KEY: ${file(./secrets/webpagetest.json):apiKey}
    GOOGLE_API_KEY: ${file(./secrets/google.json):apiKey}

functions:
  reportPerformance:
    handler: src/reportPerformance.reportPerformance
    events:
      - schedule:
          rate: rate(24 hours)
          enabled: true

package:
  include:
    - src/**
    - secrets/**
  exclude:
    - .webpack

