service: perf-monitor

plugins:
  - serverless-webpack

# package:
#   individually: true

# custom:
#   webpackIncludeModules: true # enable auto-packing of external modules

provider:
  name: aws
  runtime: nodejs6.10

# you can overwrite defaults here
#  stage: dev

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  runReporters:
    handler: src/runReporters.runReporters

package:
  include:
    - src/**
    - secrets/**
  exclude:
    - .webpack

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - schedule: rate(10 minutes)

#    Define function environment variables here
#    environment:
#      variable2: value2
